# -*- coding: utf-8 -*-
"""Holiday project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTipYS5MQINzkkg7nNr7Uj6VwsgZUKFN
"""

#Holiday _Package_Prediction by random forest using Bagging
import pandas as pd
df=pd.read_csv("Travel.csv")
df

df.head()
print(df["Gender"].value_counts())
df["TypeofContact"].value_counts()
df["Occupation"].value_counts()
df["ProductPitched"].value_counts()
print(df["MaritalStatus"].value_counts())

#3.Merging the data
df["Gender"]=df["Gender"].replace("Fe Male","Female")
df["MaritalStatus"]=df["MaritalStatus"].replace("Unmarried","Single")

#4.Handle the missimg values
null_features=[ i for i in df.columns if(df[i]).isnull().sum()>=1]
null_features

#Filling the missing values
df["Age"].fillna(df["Age"].median(),inplace=True)
df["TypeofContact"].fillna(df["TypeofContact"].mode()[0],inplace=True)
df["DurationOfPitch"].fillna(df["DurationOfPitch"].median(),inplace=True)
df["NumberOfFollowups"].fillna(df["NumberOfFollowups"].mode()[0],inplace=True)
df["PreferredPropertyStar"].fillna(df["PreferredPropertyStar"].median(),inplace=True)
df["NumberOfTrips"].fillna(df["NumberOfTrips"].median(),inplace=True)
df["NumberOfChildrenVisiting"].fillna(df["NumberOfChildrenVisiting"].median(),inplace=True)
df["MonthlyIncome"].fillna(df["MonthlyIncome"].median(),inplace=True)

#droping unwanted columns
df.drop("CustomerID",inplace=True,axis=1)

#creating the new column
df["TotalVisiting"]=df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop("NumberOfPersonVisiting",axis=1,inplace=True)
df.drop("NumberOfChildrenVisiting",axis=1,inplace=True)

#segregate the the independent and dependent features data
x=df.drop("ProdTaken",axis=1)
y=df["ProdTaken"]
#segregate the data catigorivcal and numerical
cat_features=x.select_dtypes(include="object").columns
num_features=x.select_dtypes(exclude="object").columns
cat_features

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
encode=OneHotEncoder(drop="first")
scalar=StandardScaler()
transformer=ColumnTransformer([("OneHotEncoder",encode,cat_features),("StandardScaler",scalar,num_features)])
transformer

x_train=transformer.fit_transform(x_train)
x_test=transformer.transform(x_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
model={
       "RandomForest":RandomForestClassifier(),
       "Logistic":LogisticRegression(),
       "Kneigh":KNeighborsClassifier(n_neighbors=5,p=2,algorithm="auto"),
       "Support":SVC(),
       "Naive":GaussianNB()
}
n=len(list(model))
for i in range(n):
    m=list(model.values())[i]
    m.fit(x_train,y_train)
    ypre=m.predict(x_test)
    score=accuracy_score(y_test,ypre)
    print(score)





