# -*- coding: utf-8 -*-
"""Ecommerce_sales_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfyWO_0lo3xSibe4atVqoBu1B__zxzDT

E_commerce Sales
"""

#read the data
import pandas as pd
df=pd.read_csv("Ecommerce.csv")
df

#checking the null values
#df.isnull().sum()
#df.info()
df.duplicated().sum()
#4.Handle the missimg values
null_features=[i for i in df.columns if(df[i]).isnull().sum()>=1]
null_features

print(df["Order Date"].value_counts())
print(df["Product Name"].value_counts())
print(df["Category"].value_counts())
print(df["Region"].value_counts())
print(df["Quantity"].value_counts())
print(df["Sales"].value_counts())
print(df["Profit"].value_counts())

#merging the data
df["Product Name"]=df["Product Name"].replace("Smartwatch","Smartphone")
df["Product Name"]=df["Product Name"].replace("Tablet","Laptop")
print(df["Product Name"].value_counts())

#droping unwanted columns
df.drop(columns=["Order Date","Product Name"],inplace=True,axis=1)

df

#segregate the independent variable and dependent variable
x=df.drop("Profit",axis=1)
y=df["Profit"]
#segregate the catgorical ,numerical features
cat_feartures=x.select_dtypes(include="object").columns
num_features=x.select_dtypes(exclude="object").columns

import pandas as pd

# Convert all text columns into numbers automatically
x = pd.get_dummies(x, drop_first=True)
x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
data=pd.DataFrame(x_train)
data

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
encode=OneHotEncoder(drop="first")
stand=StandardScaler()
transformer=ColumnTransformer([("OneHotEncoder",encode,OneHotEncoder),("StandardScaler",stand,num_features)])
transformer

"""x_train=transformer.fit_transform(x_train)
x_test=transformer.transform(x_test)

"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet
from sklearn.metrics import r2_score
model={

        "linear":LinearRegression(),
        "kNN":KNeighborsRegressor(n_neighbors=5,p=2,algorithm="auto"),
        "SVR":SVR(),
        "tree":DecisionTreeRegressor(),
        "forest":RandomForestRegressor(),
        "ada":AdaBoostRegressor(),
        "gradient":GradientBoostingRegressor(),
        "las":Lasso(),
        "Ri":Ridge(),
        "elas":ElasticNet()
}
n=len(list(model))
for i in range(n):
    m=list(model.values())[i]
    m.fit(x_train,y_train)
    ypre=m.predict(x_test)
    r2=r2_score(y_test,ypre)
    print(r2)
    n = x.shape[0]  # Number of rows (data points)
    p = x.shape[1]  # Number of columns (predictors)
    adjusted_r2= 1 - (1-r2) * (n - 1) / (n - p - 1)

    # Print results
    print(adjusted_r2)

